module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.places = [
    'Relaxo Pure Veg',
    'Samudra',
    'Hotel Mahendar',
    'Mamta Mess',
    'Hotel Durga',
    'Global Punjab',
    'Hotel Taj',
    'Mariott',
    'Food Mania',
    'Pimplico',
    'Sky Roof Top 9',
    'Kokpa',
    'Karishma',
    'Mamta Paratha House',
    'Filara',
    'Skygrill',
    'Guddan Ka Dhaba',
    'West Inn',
    'Lake Vinora',
    'Hotel Datta',
    'Haldiram'
]

